name: Format suggestions
on:
  pull_request:
jobs:
  code-style:
    runs-on: ubuntu-latest
    permissions:
        contents: read
        pull-requests: write
    steps:
      - uses: julia-actions/julia-format@v2
